name: flutter_notification
description: A cross platform plugin for displaying and scheduling notifications for Flutter applications with the ability to customise for each platform.
version: 1.0.6
homepage: https://github.com/hello-addweb/flutter_notification.git

dependencies:
  flutter:
    sdk: flutter
  platform: ">=2.0.0 <4.0.0"
  flutter_local_notifications_platform_interface: ^2.0.0+1
  timezone: ^0.5.6

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  plugin_platform_interface: ^1.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.addweb.flutterlocalnotifications
        pluginClass: FlutterLocalNotificationsPlugin
#      ios:
#        pluginClass: FlutterLocalNotificationsPlugin
#      macos:
#        pluginClass: FlutterLocalNotificationsPlugin


environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"